CREATE DATABASE `TWITTER`;
CREATE TABLE IF NOT EXISTS `TWITTER` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `TIME` int(10) unsigned NOT NULL,
  `NAME` text NOT NULL,
  `COMMENT` text NOT NULL,
  KEY `ID` (`ID`)
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
